/*
 * File: app/store/UserStore.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('raxa.store.UserStore', {
    extend: 'Ext.data.Store',

    requires: [
        'raxa.model.userStore',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    config: {
        autoLoad: true,
        autoSync: true,
        data: [
            {
                username: 'Ed',
                password: 'Spencer'
            },
            {
                username: 'Tommy',
                password: 'Maintz'
            },
            {
                username: 'Aaron',
                password: 'Conran'
            },
            {
                username: 'Jamie',
                password: 'Avins'
            }
        ],
        model: 'raxa.model.userStore',
        storeId: 'UserStore',
        proxy: {
            type: 'ajax',
            url: 'http://localhost/architect_project/sencha_form/UserStore.json',
            reader: {
                type: 'MyJsonReader',
                rootProperty: 'results'
            }
        }
    }
});