/*
 * File: app/controller/listTool.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('raxa.controller.listTool', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            listDocs: '#listDocs',
            clearFilter: '#clearFilter'
        },

        control: {
            "listDocs": {
                itemtap: 'showDetail'
            },
            "clearFilter": {
                tap: 'clearFilter'
            }
        }
    },

    showDetail: function(listDocs, index, target, record) {
        var body2 = "hospital : "+record.get('hospital')+"Specialization : "+record.get('Specialization')+" State :"+record.get('State')+" City :"+record.get('City');

              Ext.getCmp('hospitalName').setValue(record.get('hospital'));
              Ext.getCmp('hospitalSpec').setValue(record.get('Specialization'));
              Ext.getCmp('hospitalCity').setValue(record.get('City'));
              Ext.getCmp('hospitalState').setValue(record.get('State'));

          Ext.getCmp('hospitalInfoPanel').setHidden(false);

    },

    clearFilter: function() {
        Ext.getCmp('listDocs').getStore().clearFilter();
              Ext.getCmp('clearFilter').setHidden(true);
    }

});