/*
 * File: app/view/feedbackForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('raxa.view.feedbackForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.feedbackForm',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Slider',
        'Ext.field.TextArea',
        'Ext.Button'
    ],

    config: {
        items: [
            {
                xtype: 'fieldset',
                title: 'feedbackform',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Treatment id',
                        name: 'treatmentid'
                    },
                    {
                        xtype: 'sliderfield',
                        label: 'Rating',
                        name: 'response',
                        increment: 20
                    },
                    {
                        xtype: 'textareafield',
                        label: 'Remarks',
                        name: 'remarks'
                    }
                ]
            },
            {
                xtype: 'button',
                text: 'Submit Feedback'
            }
        ]
    }

});