/*
 * File: app/view/infoDisplay.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('raxa.view.infoDisplay', {
    extend: 'Ext.Panel',
    alias: 'widget.infodis',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Text'
    ],

    config: {
        hidden: true,
        id: 'hospitalInfoPanel',
        items: [
            {
                xtype: 'fieldset',
                id: 'hospitalInfo',
                title: 'Hospital Information',
                items: [
                    {
                        xtype: 'textfield',
                        height: '20%',
                        id: 'hospitalName',
                        label: 'Hospital Name',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        height: '20%',
                        id: 'hospitalState',
                        label: 'State',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        height: '20%',
                        id: 'hospitalCity',
                        label: 'City',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        height: '20%',
                        id: 'hospitalSpec',
                        label: 'Specialization',
                        readOnly: true
                    }
                ]
            }
        ]
    },

    initialize: function() {
        this.callParent();
    }

});