/*
 * File: app/view/listTool.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('raxa.view.listTool', {
    extend: 'Ext.dataview.List',
    alias: 'widget.searchList',

    requires: [
        'Ext.XTemplate',
        'raxa.store.hospitalstore',
        'Ext.Toolbar',
        'Ext.field.Search'
    ],

    config: {
        border: '0 1 1 1',
        id: 'listDocs',
        style: 'border-color: black; border-style: solid;',
        emptyText: '<div style="margin-top: 20px; text-align: center">No Matching Items</div>',
        grouped: true,
        itemTpl: [
            '<div class="contact"><strong>{hospital}</strong></div>'
        ]
    },

    initialize: function() {
        this.callParent();
        this.setStore(Ext.create("raxa.store.hospitalstore"));
    }

});