/*
 * File: app/view/patientForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('raxa.view.patientForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.patientForm',

    requires: [
        'raxa.view.listTool',
        'raxa.view.infoDisplay',
        'raxa.view.sortList',
        'raxa.view.mainTool',
        'Ext.form.FieldSet',
        'Ext.field.Number',
        'Ext.field.Select',
        'Ext.field.Toggle',
        'Ext.Map',
        'Ext.field.TextArea',
        'Ext.Panel',
        'Ext.dataview.List',
        'Ext.Button',
        'Ext.Menu'
    ],

    config: {
        layout: 'vbox',
        scrollable: 'vertical',
        items: [
            {
                xtype: 'fieldset',
                bottom: '50%',
                centered: false,
                height: '55%',
                left: '0%',
                right: '20%',
                top: '0%',
                title: 'patientform',
                items: [
                    {
                        xtype: 'numberfield',
                        height: '10%',
                        label: 'Patient Id',
                        name: 'id'
                    },
                    {
                        xtype: 'selectfield',
                        height: '10%',
                        label: 'Disease',
                        options: [
                            {
                                text: 'Malaria',
                                value: 'malaria'
                            },
                            {
                                text: 'Dengue',
                                value: 'dengue'
                            },
                            {
                                text: 'Typhiod',
                                value: 'typhiod'
                            }
                        ]
                    },
                    {
                        xtype: 'togglefield',
                        height: '10%',
                        label: 'Emergency',
                        name: 'Emergency',
                        activeLabel: 'Yes',
                        inactiveLabel: 'No'
                    },
                    {
                        xtype: 'togglefield',
                        height: '10%',
                        label: 'Location Detect',
                        name: 'detectLocation'
                    },
                    {
                        xtype: 'map',
                        height: '35%',
                        itemId: 'map2',
                        useCurrentLocation: true
                    },
                    {
                        xtype: 'textareafield',
                        height: '15%',
                        label: 'Additional Information',
                        name: 'info',
                        placeHolder: 'Enter your symptoms/condition'
                    }
                ]
            },
            {
                xtype: 'panel',
                flex: 1,
                docked: 'left',
                height: '100%',
                id: 'list',
                width: '20%',
                layout: 'fit',
                items: [
                    {
                        xtype: 'searchList',
                        height: '100%'
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 3,
                bottom: '0%',
                height: '30%',
                id: 'info',
                left: '0%',
                right: '20%',
                styleHtmlContent: true,
                top: '60%',
                layout: 'card',
                items: [
                    {
                        xtype: 'infodis',
                        docked: 'top',
                        floatingCls: 'x-panel',
                        height: '100%',
                        width: '100%'
                    }
                ]
            },
            {
                xtype: 'panel',
                flex: 1.2,
                floatingCls: 'x-panel',
                height: '40%',
                id: 'filter',
                left: '80%',
                right: '0%',
                width: '20%',
                layout: 'card',
                items: [
                    {
                        xtype: 'sort',
                        height: 278,
                        scrollable: false
                    }
                ]
            },
            {
                xtype: 'mainTool',
                floatingCls: 'x-panel',
                right: '0%',
                top: '45%',
                width: '20%'
            },
            {
                xtype: 'button',
                docked: 'bottom',
                itemId: 'patientButton',
                text: 'submit'
            }
        ]
    },

    initialize: function() {
        this.callParent();
        Ext.getCmp('filter1').setLeft(Ext.getCmp('mainSearch').getWidth());
    }

});