/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({

    requires: [
        'Ext.MessageBox'
    ],
    models: [
        'Model',
        'Location'
    ],
    stores: [
        'Locations',
        'PlacesStore'
    ],
    views: [
        'MainView',
        'LoginForm',
        'RegisterForm',
        'WelcomePanel',
        'patientForm',
        'feedbackForm',
        'notificationpanel',
        'FormPanel',
        'NavigationView'
    ],
    controllers: [
        'Account'
    ],
    name: 'raxa',

    launch: function() {

        Ext.create('raxa.view.NavigationView', {fullscreen: true});
    }

});
